export type Creator = {
  slug: string
  name: string
  category: string
  location: string
  image: string
  bio: string[]
  stats: { value: string; label: string }[]
  socials: { label: string; href: string; handle?: string }[]
}

export const creatorCategories = [
  "All",
  "Streamers",
  "Short Form",
  "Long Form",
  "Videographers",
  "Photographers",
  "Animators",
  "Illustrators",
  "Copywriters",
  "Models",
  "Athletes",
  "Hosts",
] as const

// TODO(owner): PLACEHOLDER DATA — replace with the real creator roster before launch. Demo records generated by v0.
export const creators: Creator[] = [
  {
    slug: "marcus-cole",
    name: "Marcus Cole",
    category: "Athletes",
    location: "Johannesburg, ZA",
    image: "/images/creators/marcus.png",
    bio: [
      "Marcus Cole is a professional footballer turned content creator whose energy on and off the pitch has built a loyal following across the continent. Known for his matchday vlogs and training breakdowns, he brings authenticity to every brand he works with.",
      "As part of the JDT roster, Marcus partners with sportswear, nutrition and lifestyle brands, blending elite athleticism with relatable storytelling that resonates with a young, active audience.",
    ],
    stats: [
      { value: "1.8M", label: "Instagram" },
      { value: "2.4M", label: "TikTok" },
      { value: "640K", label: "YouTube" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "elena-frost",
    name: "Elena Frost",
    category: "Long Form",
    location: "Cape Town, ZA",
    image: "/images/creators/elena.png",
    bio: [
      "Elena Frost is a lifestyle and travel creator whose cinematic vlogs and honest reviews have made her one of the most trusted voices in her niche. Her audience tunes in for genuine recommendations and beautifully shot stories.",
      "With JDT, Elena collaborates with travel, tech and lifestyle brands, delivering polished campaigns that feel personal rather than promotional.",
    ],
    stats: [
      { value: "920K", label: "Instagram" },
      { value: "1.5M", label: "TikTok" },
      { value: "410K", label: "YouTube" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "dineo-mokoena",
    name: "Dineo Mokoena",
    category: "Models",
    location: "Durban, ZA",
    image: "/images/creators/dineo.png",
    bio: [
      "Dineo Mokoena is a fashion model and creative whose striking presence has graced campaigns for some of the region's boldest brands. Her eye for styling and confident delivery make her a natural fit for fashion and beauty partnerships.",
      "Through JDT, Dineo works with fashion houses, beauty labels and editorial teams, bringing both runway polish and digital-native content skills to every shoot.",
    ],
    stats: [
      { value: "740K", label: "Instagram" },
      { value: "510K", label: "TikTok" },
      { value: "180K", label: "YouTube" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "jay-rivers",
    name: "Jay Rivers",
    category: "Streamers",
    location: "Pretoria, ZA",
    image: "/images/creators/jay.png",
    bio: [
      "Jay Rivers is a gaming streamer and personality whose high-energy broadcasts and community-first approach have grown a dedicated fanbase. From live tournaments to reaction content, Jay keeps audiences engaged for hours.",
      "As a JDT creator, Jay partners with gaming, tech and energy brands, offering authentic integrations that land with a hard-to-reach Gen Z audience.",
    ],
    stats: [
      { value: "560K", label: "Twitch" },
      { value: "1.1M", label: "TikTok" },
      { value: "880K", label: "YouTube" },
    ],
    socials: [
      { label: "Twitch", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "tariq-bello",
    name: "Tariq Bello",
    category: "Athletes",
    location: "Lagos, NG",
    image: "/images/creators/tariq.png",
    bio: [
      "Tariq Bello is a football freestyler whose jaw-dropping skills have earned him viral fame and collaborations with major sports brands. His content blends technical mastery with infectious charisma.",
      "With JDT, Tariq creates branded skill content, appears at activations and headlines campaigns that demand real athletic credibility.",
    ],
    stats: [
      { value: "2.1M", label: "Instagram" },
      { value: "3.6M", label: "TikTok" },
      { value: "1.2M", label: "YouTube" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "sofia-vance",
    name: "Sofia Vance",
    category: "Short Form",
    location: "Cape Town, ZA",
    image: "/images/creators/sofia.png",
    bio: [
      "Sofia Vance is a beauty and lifestyle influencer known for her warm, approachable content and trusted product reviews. Her followers rely on her honest takes across skincare, fashion and wellness.",
      "Through JDT, Sofia leads beauty launches, runs long-term ambassador deals and produces UGC that consistently outperforms for brand partners.",
    ],
    stats: [
      { value: "1.3M", label: "Instagram" },
      { value: "990K", label: "TikTok" },
      { value: "320K", label: "YouTube" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "kai-mensah",
    name: "Kai Mensah",
    category: "Photographers",
    location: "Accra, GH",
    image: "/images/creators/kai.png",
    bio: [
      "Kai Mensah is a photographer and visual storyteller whose distinctive style has defined campaigns for fashion, music and lifestyle brands. Behind the lens or in front of it, Kai shapes culture.",
      "As part of the JDT roster, Kai directs shoots, produces branded photo series and mentors emerging creators across the network.",
    ],
    stats: [
      { value: "480K", label: "Instagram" },
      { value: "260K", label: "TikTok" },
      { value: "95K", label: "Behance" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "Behance", href: "#" },
    ],
  },
  {
    slug: "amara-johnson",
    name: "Amara Johnson",
    category: "Hosts",
    location: "Johannesburg, ZA",
    image: "/images/creators/amara.png",
    bio: [
      "Amara Johnson is a television and event host whose confident delivery and quick wit make her a favourite for live broadcasts, brand events and red carpets. She commands a room and a camera with ease.",
      "With JDT, Amara fronts brand campaigns, hosts activations and lends her trusted voice to partnerships across entertainment and lifestyle.",
    ],
    stats: [
      { value: "650K", label: "Instagram" },
      { value: "430K", label: "TikTok" },
      { value: "210K", label: "YouTube" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "TikTok", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "leo-hart",
    name: "Leo Hart",
    category: "Videographers",
    location: "Cape Town, ZA",
    image: "/images/creators/leo.png",
    bio: [
      "Leo Hart is a videographer and director whose cinematic eye has shaped commercials, music videos and brand films across the continent. He turns briefs into stories that move, with a craft honed on set after set.",
      "As part of the JDT roster, Leo leads end-to-end production — from concept and shoot to the final grade — delivering broadcast-quality films for brands that want to be remembered.",
    ],
    stats: [
      { value: "120+", label: "Productions" },
      { value: "38", label: "Brand Films" },
      { value: "9", label: "Awards" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "Vimeo", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
  {
    slug: "nadia-khan",
    name: "Nadia Khan",
    category: "Animators",
    location: "Durban, ZA",
    image: "/images/creators/nadia.png",
    bio: [
      "Nadia Khan is a motion designer and animator who brings brands to life through 2D and 3D animation, title sequences and explainer content. Her work balances technical polish with a real sense of play.",
      "Through JDT, Nadia produces motion graphics for campaigns, social and broadcast — translating complex ideas into frames that feel effortless.",
    ],
    stats: [
      { value: "260+", label: "Projects" },
      { value: "45", label: "Brands" },
      { value: "12", label: "Years" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "Behance", href: "#" },
      { label: "Dribbble", href: "#" },
    ],
  },
  {
    slug: "theo-banks",
    name: "Theo Banks",
    category: "Illustrators",
    location: "Johannesburg, ZA",
    image: "/images/creators/theo.png",
    bio: [
      "Theo Banks is an illustrator and digital artist whose bold, characterful style has defined packaging, editorial and campaign work for culture-forward brands. Every piece carries a distinct point of view.",
      "With JDT, Theo creates custom illustration systems, key art and brand worlds that give partners an instantly recognisable visual identity.",
    ],
    stats: [
      { value: "300+", label: "Commissions" },
      { value: "60", label: "Brands" },
      { value: "150K", label: "Behance" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "Behance", href: "#" },
      { label: "Dribbble", href: "#" },
    ],
  },
  {
    slug: "maya-lindt",
    name: "Maya Lindt",
    category: "Copywriters",
    location: "Cape Town, ZA",
    image: "/images/creators/maya.png",
    bio: [
      "Maya Lindt is a copywriter and brand strategist who turns positioning into language people actually remember. From taglines to long-form campaigns, she finds the line that makes a brand click.",
      "As part of the JDT roster, Maya shapes brand voice, writes launch campaigns and crafts the words behind activations, scripts and social.",
    ],
    stats: [
      { value: "200+", label: "Campaigns" },
      { value: "70", label: "Brands" },
      { value: "11", label: "Years" },
    ],
    socials: [
      { label: "Instagram", href: "#" },
      { label: "LinkedIn", href: "#" },
      { label: "Portfolio", href: "#" },
    ],
  },
]

export function getCreatorBySlug(slug: string) {
  return creators.find((c) => c.slug === slug)
}
