export type ProjectCategory = "Printing & Design" | "Talent Management" | "AI & Development"

export type Project = {
  slug: string
  title: string
  client: string
  category: ProjectCategory
  industry: string
  year: string
  image: string
  summary: string
}

export const projectCategories: ProjectCategory[] = [
  "Printing & Design",
  "Talent Management",
  "AI & Development",
]

// TODO(owner): PLACEHOLDER DATA — replace with real projects before launch. Demo records generated by v0.
export const projects: Project[] = [
  {
    slug: "campaign-print-suite",
    title: "Campaign Print Suite",
    client: "Meridian Group",
    category: "Printing & Design",
    industry: "Retail",
    year: "2024",
    image: "/images/work-print-1.png",
    summary: "A full print campaign spanning flyers, brochures and in-store collateral for a national retail launch.",
  },
  {
    slug: "studio-talent-shoot",
    title: "Studio Talent Shoot",
    client: "NovaTech",
    category: "Talent Management",
    industry: "Technology",
    year: "2024",
    image: "/images/work-talent-1.png",
    summary: "Casting, direction and production for a flagship brand campaign featuring our managed talent roster.",
  },
  {
    slug: "ecommerce-platform",
    title: "E-Commerce Platform",
    client: "Apex Retail",
    category: "AI & Development",
    industry: "E-commerce",
    year: "2025",
    image: "/images/work-ai-1.png",
    summary: "A custom storefront with AI-powered product recommendations and a headless content backend.",
  },
  {
    slug: "retail-packaging-line",
    title: "Retail Packaging Line",
    client: "Lumière Beauty",
    category: "Printing & Design",
    industry: "Beauty",
    year: "2024",
    image: "/images/work-print-2.png",
    summary: "End-to-end packaging design and production for a premium beauty product range.",
  },
  {
    slug: "live-brand-activation",
    title: "Live Brand Activation",
    client: "Pulse Fitness",
    category: "Talent Management",
    industry: "Fitness",
    year: "2025",
    image: "/images/work-talent-2.png",
    summary: "Brand ambassadors and event talent for a high-energy nationwide activation tour.",
  },
  {
    slug: "customer-mobile-app",
    title: "Customer Mobile App",
    client: "Orion Logistics",
    category: "AI & Development",
    industry: "Logistics",
    year: "2025",
    image: "/images/work-ai-2.png",
    summary: "A cross-platform mobile app with real-time tracking and an AI support assistant.",
  },
  {
    slug: "editorial-magazine",
    title: "Editorial Magazine",
    client: "Vanguard Media",
    category: "Printing & Design",
    industry: "Publishing",
    year: "2023",
    image: "/images/work-print-3.png",
    summary: "Art direction, layout and print production for a quarterly premium editorial title.",
  },
  {
    slug: "tv-commercial-production",
    title: "TV Commercial Production",
    client: "Solstice Hotels",
    category: "Talent Management",
    industry: "Hospitality",
    year: "2024",
    image: "/images/work-talent-3.png",
    summary: "Talent casting and on-set management for a national television commercial campaign.",
  },
  {
    slug: "analytics-dashboard",
    title: "Analytics Dashboard",
    client: "Bluepeak Finance",
    category: "AI & Development",
    industry: "Finance",
    year: "2025",
    image: "/images/work-ai-3.png",
    summary: "A real-time analytics dashboard with predictive AI insights for financial decision-making.",
  },
]

export const featuredProjects = projects.slice(0, 3)
