export type ServiceCategory = {
  id: string
  slug: string
  label: string
  tagline: string
  description: string
  image: string
  services: { name: string; description: string }[]
}

// TODO(owner): PLACEHOLDER DATA — replace with real services before launch. Demo records generated by v0.
export const serviceCategories: ServiceCategory[] = [
  {
    id: "printing-design",
    slug: "printing-and-design",
    label: "Design, Print & Media",
    tagline: "From concept to print-ready, we make your brand impossible to ignore.",
    description:
      "Great brands deserve flawless execution. From one-off displays to complete brand deployments, we manage the process from concept to delivery, ensuring every detail is refined, every colour is accurate, and every asset reflects the quality of your business.",
    image: "/images/showcase-print.png",
    services: [
      { name: "Brand Identity & Logo Design", description: "Logos, Brand Guidelines and Full Identity Systems" },
      { name: "Litho & Large Format Printing", description: "Posters, Banners & Signage" },
      { name: "Videography, Photography, Animation & Post-Production", description: "Directing, Sound Design, VFX & Storytelling" },
      { name: "Bespoke Apparel & Merchandise", description: "Pattern Engineering, Custom Garments & Countless Branding Methods" },
      { name: "Social Media & Digital Design", description: "End-to-End SMM, 2D, 3D, Motion Graphics, Posting and Copywriting" },
      { name: "Bespoke Packaging, Labels & Stickers", description: "Bespoke Boxes, Bags & Carriers, Cartons & Stationery" },
      { name: "Brochures, Catalogues & Publications", description: "Leaflets, Calendars, Magazines, Restaurant Menus & Catalogues" },
      { name: "Custom Corporate Gifts", description: "Branded Gifts, Tailored Boxes that clients actually keep" },
      { name: "Event Branding & Activations", description: "Shop-fitting, Exhibitions, Mall Activations & Experiential Events" },
      { name: "Laser Cutting & Engraving", description: "Cutting, Engraving & Marking of Steel, Brass, Acrylic and Wood" },
      { name: "Custom Display Units", description: "Stands, Counters and Point-of-Sale Displays" },
      { name: "Luxury Print & Finishing", description: "Foiling, Embossing, Debossing & Finishes that leave an impression" },
    ],
  },
  {
    id: "talent-management",
    slug: "talent-management",
    label: "Talent Management",
    tagline: "The right faces and voices for your brand, managed end to end.",
    description:
      "We represent and manage a roster of creators, models, athletes and presenters — and we match them to brands that fit. From first brief to final deliverable, we handle contracts, logistics and campaign delivery so collaborations run smoothly.",
    image: "/images/showcase-talent.png",
    services: [
      { name: "Influencer Management", description: "Sourcing, contracting and campaign delivery" },
      { name: "Model & Talent Booking", description: "Models, actors and presenters for any brief" },
      { name: "Brand Ambassadors", description: "Trained reps who live your brand" },
      { name: "Event Staffing", description: "Promo teams, hosts and activation crews" },
      { name: "Casting & Scouting", description: "Finding fresh faces that fit your vision" },
      { name: "Content Creator Partnerships", description: "UGC creators matched to your audience" },
      { name: "Campaign Management", description: "Full-service talent campaign execution" },
      { name: "Social Media Management", description: "Channels run by people who get culture" },
      { name: "Talent Development", description: "Coaching and growing emerging talent" },
      { name: "Photo & Video Shoots", description: "Production days with talent included" },
    ],
  },
  {
    id: "ai-development",
    slug: "ai-and-development",
    label: "AI & Development",
    tagline: "Modern builds and AI workflows that move faster than your competitors.",
    description:
      "Our engineers and AI specialists build the digital products that power modern brands — from conversion-focused websites to bespoke AI tooling. We ship fast, design around real users and keep everything fast, secure and online.",
    image: "/images/showcase-ai.png",
    services: [
      { name: "Web Design & Development", description: "Fast, beautiful websites built to convert" },
      { name: "E-commerce Stores", description: "Online shops that are easy to run and scale" },
      { name: "Mobile Apps", description: "iOS and Android apps your customers love" },
      { name: "AI Chatbots & Assistants", description: "Customer support that never sleeps" },
      { name: "AI Content & Automation", description: "Workflows that save hours every week" },
      { name: "AI Image & Video Generation", description: "On-brand visuals at the speed of AI" },
      { name: "UI/UX Design", description: "Interfaces designed around real users" },
      { name: "Custom Software", description: "Tools built for exactly how you work" },
      { name: "SEO & Analytics", description: "Get found, measure everything" },
      { name: "Hosting & Maintenance", description: "We keep it fast, secure and online" },
    ],
  },
]

export function getCategoryBySlug(slug: string) {
  return serviceCategories.find((c) => c.slug === slug)
}

export const trustedBrands = [
  "Northway Group",
  "Velocity Motors",
  "Cassidy & Co.",
  "Bluestone Events",
  "Harbour Lane",
  "Atlas Fitness",
  "Mara Beauty",
  "Stockman Breweries",
  "Pinnacle Realty",
  "Fjord Outdoors",
  "Lumen Health",
  "Crown & Anchor",
]
